#!/usr/bin/env python3
"""
================================================================================
report.py  -  auto-generate a paper-style report of a full LASERSIM run
================================================================================
Runs the whole system pipeline and emits a self-contained, publication-style
report: an abstract, the stage-by-stage energy table, the B-integral safety
audit, thermal-lens summary, and a model-vs-paper comparison, all formatted the
way the source paper presents its Table 1 / Table 2.

Output formats:
  * HTML  (always; no extra deps) -> report.html
  * PDF   (if `reportlab` is installed) -> report.pdf

This is what you hand a supervisor or drop into a thesis appendix.

Run:
    python report.py                 # writes report.html
    python report.py --pdf           # also writes report.pdf (needs reportlab)
================================================================================
"""
from __future__ import annotations

import argparse
import datetime as _dt
from typing import List

from full_system import run_full_system, StageAudit
from amplifier import PAPER_B
from thermal_abcd import ThermalRod, diode_current_to_pump


TITLE = "LASERSIM Simulation Report: All-Diode-Pumped 1.28 J / 200 ps Nd:YAG Amplifier"
ABSTRACT = (
    "This report presents a full end-to-end simulation of an all-diode-pumped "
    "Nd:YAG laser amplifier delivering ~1.28 J in <200 ps pulses at 10 Hz, "
    "reproduced with the LASERSIM platform. The seed is amplified through a "
    "two-pass pre-amplifier (AMP-1), apodized by a serrated aperture, further "
    "amplified in a second two-pass stage (AMP-2), spatially filtered, and "
    "boosted in a final single-pass dual-module stage (AMP-3). Energy extraction "
    "is modeled with the Frantz-Nodvik formalism; nonlinearity is tracked via "
    "the B-integral with a 2/3 reduction for circular polarization. Modeled "
    "stage energies and B-integrals are compared against the published values."
)


def _rows_html(audits: List[StageAudit]) -> str:
    out = []
    for a in audits:
        d = a.delta_pct()
        out.append(
            "<tr>"
            f"<td>{a.stage}</td>"
            f"<td>{a.e_in_mJ:.0f}</td>"
            f"<td>{a.e_out_mJ:.0f}</td>"
            f"<td>{a.gain:.2f}</td>"
            f"<td>{a.peak_fluence:.2f}</td>"
            f"<td>{a.b_integral:.2f}</td>"
            f"<td>{a.f_th_cm if a.f_th_cm else '-'}</td>"
            f"<td>{a.paper_mJ if a.paper_mJ else '-'}</td>"
            f"<td>{f'{d:+.1f}%' if d is not None else '-'}</td>"
            "</tr>"
        )
    return "\n".join(out)


def build_html(audits: List[StageAudit]) -> str:
    final = audits[-1].e_out_mJ
    peak_B = max(a.b_integral for a in audits)
    pump_W = diode_current_to_pump(120.0)
    f15 = ThermalRod(radius_m=7.5e-3).focal_length(pump_W) * 100
    f25 = ThermalRod(radius_m=12.5e-3).focal_length(pump_W) * 100
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>{TITLE}</title>
<style>
  body {{ font-family: Georgia, 'Times New Roman', serif; max-width: 820px;
          margin: 40px auto; color: #1a1a1a; line-height: 1.5; }}
  h1 {{ font-size: 1.5rem; border-bottom: 2px solid #333; padding-bottom: 8px; }}
  h2 {{ font-size: 1.1rem; margin-top: 1.8em; color: #222; }}
  .meta {{ color: #666; font-size: 0.85rem; }}
  .abstract {{ background: #f6f6f6; padding: 16px 20px; border-left: 4px solid #555;
               font-size: 0.95rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1em 0; font-size: 0.9rem; }}
  th, td {{ border: 1px solid #ccc; padding: 6px 9px; text-align: right; }}
  th:first-child, td:first-child {{ text-align: left; }}
  th {{ background: #efefef; }}
  .ok {{ color: #137333; font-weight: bold; }}
  .risk {{ color: #b00020; font-weight: bold; }}
  footer {{ margin-top: 3em; color: #888; font-size: 0.8rem;
            border-top: 1px solid #ddd; padding-top: 10px; }}
</style></head>
<body>
  <h1>{TITLE}</h1>
  <div class="meta">Generated by LASERSIM &middot; {now}</div>
  <h2>Abstract</h2>
  <div class="abstract">{ABSTRACT}</div>

  <h2>Stage-by-stage results (model vs. published)</h2>
  <table>
    <tr><th>Stage</th><th>E_in (mJ)</th><th>E_out (mJ)</th><th>Gain</th>
        <th>Peak F (J/cm&sup2;)</th><th>B (rad)</th><th>f_th (cm)</th>
        <th>Paper (mJ)</th><th>&Delta;</th></tr>
    {_rows_html(audits)}
  </table>

  <h2>Summary</h2>
  <p>Modeled final output: <b>{final:.0f} mJ</b> (published: 1280 mJ).</p>
  <p>Peak B-integral across the chain: <b>{peak_B:.2f} rad</b>
     <span class="{'ok' if peak_B < 3 else 'risk'}">
     ({'within' if peak_B < 3 else 'ABOVE'} the ~3 rad self-focusing safe limit)</span>.</p>
  <p>Thermal-lens focal length at 120 A: {f15:.1f} cm (15 mm rods),
     {f25:.1f} cm (25 mm rods).</p>
  <p>Published B-integrals (GM1&ndash;GM4): {PAPER_B}.</p>

  <footer>
    Reference: K. Raza et al., "An all-diode pumped 1.28-Joule, 200-picosecond
    Nd:YAG laser amplifier at 10 Hz," Optics Communications 577 (2025) 131413.
    Simulation: LASERSIM (github.com/abdulbasit742/lasersim).
  </footer>
</body></html>
"""


def write_pdf(audits: List[StageAudit], path: str = "report.pdf") -> bool:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle)
        from reportlab.lib.styles import getSampleStyleSheet
    except Exception:
        return False

    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(path, pagesize=A4)
    flow = [Paragraph(TITLE, styles["Title"]), Spacer(1, 8),
            Paragraph("<b>Abstract.</b> " + ABSTRACT, styles["BodyText"]),
            Spacer(1, 14)]
    data = [["Stage", "E_in", "E_out", "Gain", "Fpk", "B", "Paper"]]
    for a in audits:
        data.append([a.stage, f"{a.e_in_mJ:.0f}", f"{a.e_out_mJ:.0f}",
                     f"{a.gain:.2f}", f"{a.peak_fluence:.2f}",
                     f"{a.b_integral:.2f}",
                     f"{a.paper_mJ:.0f}" if a.paper_mJ else "-"])
    t = Table(data, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
    ]))
    flow.append(t)
    final = audits[-1].e_out_mJ
    flow.append(Spacer(1, 12))
    flow.append(Paragraph(f"Modeled final output: <b>{final:.0f} mJ</b> "
                          f"(published 1280 mJ).", styles["BodyText"]))
    doc.build(flow)
    return True


def main():
    ap = argparse.ArgumentParser(description="Generate a LASERSIM report")
    ap.add_argument("--pdf", action="store_true", help="also emit report.pdf")
    ap.add_argument("--out", default="report.html")
    args = ap.parse_args()

    audits = run_full_system()
    html = build_html(audits)
    with open(args.out, "w") as fh:
        fh.write(html)
    print(f"Wrote {args.out}")
    if args.pdf:
        ok = write_pdf(audits)
        print("Wrote report.pdf" if ok else
              "reportlab not installed -> skipped PDF (pip install reportlab)")


if __name__ == "__main__":
    main()
