apiVersion: v1
kind: Pod
metadata:
  name: kmode-gpu-inference
spec:
  containers:
    - name: kmode-api
      image: lasersim/kmode-api:latest
      resources:
        limits:
          nvidia.com/gpu: 1
  nodeSelector:
    accelerator: nvidia
